spring:
  profiles:
    active: dev                                                              
  mvc:
    view:
      prefix: /view/
      suffix: .jsp
  http:
    encoding:
      charset: UTF-8
      enabled: true
   
---
spring:                                                     
  profiles: dev   
server:
  port: 8080                                             
  context-path: /EncryptionApp
AES:
  key: test1234test1234test1234test1234
RSA:
  publicKey: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDZAylc+f3AHjRW7JEBt2FFf2zttZ/YguhrDcW7fErOWRk1QIttnUoU9qvuljnEpwXeRJ0ygoVy+FFv9OOMKGBueQAnELIUpocwotJxi9eiaDcdqr7olQ5CM3C4fYlTC4tgR+BsaT9Co8jCF/Ai2XK7YDZrnaJeA1l8UeSZT2nGRwIDAQAB
  privateKey: MIICeAIBADANBgkqhkiG9w0BAQEFAASCAmIwggJeAgEAAoGBANkDKVz5/cAeNFbskQG3YUV/bO21n9iC6GsNxbt8Ss5ZGTVAi22dShT2q+6WOcSnBd5EnTKChXL4UW/044woYG55ACcQshSmhzCi0nGL16JoNx2qvuiVDkIzcLh9iVMLi2BH4GxpP0KjyMIX8CLZcrtgNmudol4DWXxR5JlPacZHAgMBAAECgYAA8L6RJJQw7PCVH9lRBJZrUq4KKatTqN2Q+TJOKa+5TTGKxYjVJMVZaeg81HHTpFWmLO3xdhdV9DWGIq2JwfMJBXkdiqHMY/2mKgMUbcspYrVKsx3ebJWwRqKxe9C68Y7w6HcApQGloQgK0oH67xQj2AOlkHa+jZ85AAsoiMBvgQJBAPvBbCpceiKF2r9HXvmy4Ae7maBfY5hNxRym4znnUMFpuzpW0dSk+VkRUR0hYgMZ4+0TW2md/MoDlrPs18s9OncCQQDcq8mMyd1o7V1n1JcxKRrVDhPlzee7v7Z8rOFs56J66VZDs98UVwJe2AYeI/0tt48ysd2f6Gu17pNZUWA+yvaxAkEAqjeqQa4LKkJkl4XTEnM+BBx0j7lPJpAWoPu5kNH0iQFLBPPkpajxqqYJuO90THJ56DZ5TRzz6Uap43dUpGb+mwJBAMSSkvxDZmRt7eLsUbKNN0XLQJZZkbCB2wG8zyLARNDQwvOUa4gm6gmqzehTjtkGxx0VrKMh27E5UTEjeGT3UEECQQC+tgKPd08mHORhXbmw+OCeZ79e4nV0MZ5efJk00WxH+gtqUCjwVoRrCjWRmSWUoCmJTbqXzKr8xQhpnOy0VWSg
PBE:
  key: PBEKey